### PR TITLE
Study case4

### PR DESCRIPTION
**Pull request by haik1803**

### CODE REVIEW

**Comment by jchacana** [comment]
Hello Hai.
Your branch currently has conflicts so it won't merge. Make sure your branch doesn't have any conflicts before merging.

Others:

- You're not persisting transactions. Each new transaction should be persisted
- A good test would be to generate a fund transfer and then query the last 10 transactions. The transaction should be there and should be the most recent one
- Your tests aren't working anymore after adding JPA, how are they supposed to work?
- Last 10 Transactions query can be rewritten without the need of a native query. Check for "JPA query methods"

Please fix this. Thanks

**Comment by haik1803** [comment]
> Hello Hai.
> Your branch currently has conflicts so it won't merge. Make sure your branch doesn't have any conflicts before merging.
> 
> Others:
> 
> * You're not persisting transactions. Each new transaction should be persisted
Hai respond:### 




> *

 A good test would be to generate a fund transfer and then query the last 10 transactions. The transaction should be there and should be the most recent one
> * Your tests aren't working anymore after adding JPA, how are they supposed to work?
> * Last 10 Transactions query can be rewritten without the need of a native query. Check for "JPA query methods"
> 
> Please fix this. Thanks

Hello @jchacana:



> Hello Hai.
> Your branch currently has conflicts so it won't merge. Make sure your branch doesn't have any conflicts before merging.
> 
> Others:
> 
> * You're not persisting transactions. Each new transaction should be persisted
> * A good test would be to generate a fund transfer and then query the last 10 transactions. The transaction should be there and should be the most recent one
> * Your tests aren't working anymore after adding JPA, how are they supposed to work?
> * Last 10 Transactions query can be rewritten without the need of a native query. Check for "JPA query methods"
> 
> Please fix this. Thanks

**Comment by haik1803** [comment]
> Hello Hai.
> Your branch currently has conflicts so it won't merge. Make sure your branch doesn't have any conflicts before merging.
> 
> Others:
> 
> * You're not persisting transactions. Each new transaction should be persisted
> * A good test would be to generate a fund transfer and then query the last 10 transactions. The transaction should be there and should be the most recent one
> * Your tests aren't working anymore after adding JPA, how are they supposed to work?
> * Last 10 Transactions query can be rewritten without the need of a native query. Check for "JPA query methods"
> 
> Please fix this. Thanks

Hi @jchacana:
Thanks for your comments. 
with point 1: 

> You're not persisting transactions. Each new transaction should be persisted.

I persist a new transaction when user click the button 'Confirm'.

**Comment by jchacana** [comment]
Please provide the tests specified here 

https://github.com/Mitrais/java-bootcamp-working/wiki/Review-Bootify-The-Application

**Comment by haik1803** [comment]
@jchacana i have written tests which you mentioned and merged into master. Please check it for me

**Pull request closed without merging**
